export const ProductsData = [
  {
    id: 1,
    sku: "pp5006301526",
    name: "Redmi Note 13 Pro (Midnight Black, 8GB RAM, 128GB Storage)",
    description:
      "The Redmi Note 13 Pro in Midnight Black offers a seamless blend of style and performance. With its sleek design and powerful features, including 8GB of RAM and 128GB of storage, it caters to the needs of modern smartphone users. Whether it's multitasking, gaming, or capturing memories with its advanced camera system, this device excels in every aspect. Experience smooth performance and stunning visuals on its high-resolution display, making it an ideal companion for both work and play.",
    list_price: 28999,
    sale_price: 24999,
    category: "mobile",
    average_product_rating: 4.6,
    image_url: "https://m.media-amazon.com/images/I/7169hX0S18L._SL1500_.jpg",
    brand: "Redmi",
    num_reviews: 49,
    Avaiable: true,
    Stocks: 45,
    keywords: ["mobile", "electronics", "redmi"],
    deliveryInDays: 5,
    cod: true,
    gender: "universal",
  },
  {
    id: 2,
    sku: "pp5004990861",
    name: "Apple iPad (10th Generation)",
    description:
      "The Apple iPad (10th Generation) is a tablet with a 10.9-inch Liquid Retina display, A14 Bionic chip, 64 GB of storage, and Wi-Fi 6 and 5G cellular connectivity. It has a 12 MP front camera and a 12 MP wide back camera, and supports 4K, 1080p, and 720p video resolution. The iPad also has a USB-C connector for charging and accessories, and is compatible with the Apple Pencil (USB-C), Apple Pencil (1st generation), and Magic Keyboard Folio.",
    list_price: 44900,
    sale_price: 37800,
    category: "tablet",
    average_product_rating: 5,
    image_url: "https://m.media-amazon.com/imagexs/I/61uA2UVnYWL._SL1500_.jpg",
    brand: "Apple",
    num_reviews: 918,
    Avaiable: true,
    Stocks: 80,
    keywords: ["tablet", "electronics", "apple"],
    deliveryInDays: 2,
    cod: true,
    gender: "universal",
  },
  {
    id: 3,
    sku: "pp5005630198",
    name: "POCO C65 Pastel Blue 8GB RAM 256GB ROM",
    description:
      "The POCO C65 Pastel Blue 8GB RAM 256GB ROM is a mid-range smartphone that is available in India. It is powered by a MediaTek Helio G85 processor and has a 6.74-inch HD+ display with a 90Hz refresh rate. The phone also has a triple-camera system on the back, consisting of a 50MP main sensor, an ultrawide sensor, and a depth sensor. The front-facing camera is 8MP.",
    list_price: 13500,
    sale_price: 8500,
    category: "mobile",
    average_product_rating: 3.8,
    image_url: "https://m.media-amazon.com/images/I/51Zjp5fq1EL._SL1100_.jpg",
    brand: "POCO",
    num_reviews: 171,
    Avaiable: true,
    Stocks: 80,
    keywords: ["mobile", "electronics", "poco"],
    deliveryInDays: 3,
    cod: true,
    gender: "universal",
  },
  {
    id: 4,
    sku: "pp5006510943",
    name: "Jockey IM21 Men's Super Combed Supima Cotton Solid Round Neck Half Sleeve T-Shirt",
    description:
      "The Jockey IM21 Men's Super Combed Supima Cotton Solid Round Neck Half Sleeve T-Shirt is a crewneck t-shirt made from, as the name suggests, super combed Supima cotton. Supima cotton is a type of Pima cotton grown in the United States that is known for its extra-long staple fibers. These long fibers make for a softer, stronger, and more durable fabric than regular cotton.",
    list_price: 799,
    sale_price: 749,
    category: "tshirt",
    average_product_rating: 4.1,
    image_url: "https: //m.media-amazon.com/images/I/61RHz1EE64L._SL1500_.jpg",
    brand: "Jockey",
    num_reviews: 395,
    Avaiable: true,
    Stocks: 116,
    keywords: ["tshirt", "clothing", "jockey"],
    deliveryInDays: 3,
    cod: true,
    gender: "mens",
  },
  {
    id: 5,
    sku: "pp5006790242",
    name: "SWORNOF Women's Banarasi Patola Silk Blend Saree ",
    description:
      "This saree is a great option for those who want the look of a luxurious Banarasi Patola saree at a more accessible price point. It's perfect for festive occasions, weddings, or any event where you want to add a touch of elegance and cultural flair.This saree is a blend of cotton and silk, making it more affordable than a pure silk saree. While it might not be as soft and breathable, the cotton blend offers easier care and durability.",
    list_price: 3500,
    sale_price: 1800,
    category: "saree",
    average_product_rating: 4.6,
    image_url: "https://m.media-amazon.com/images/I/61OlJMyBvxS._SL1080_.jpg",
    brand: "SWORNOF",
    num_reviews: 1191,
    Avaiable: true,
    Stocks: 12,
    keywords: ["saree", "clothing", "swornof"],
    deliveryInDays: 3,
    cod: true,
    gender: "womens",
  },
  {
    id: 6,
    sku: "pp5004070589",
    name: "Puma Men's T-Shirt",
    description:
      "This is a Puma t-shirt designed for everyday wear. It's likely a crewneck t-shirt made from breathable cotton. The  'Archive Green' color suggests a darker or muted green shade. It also has a two-color logo on the front, but without an image it's difficult to say exactly what the logo looks like.",
    list_price: 1600,
    sale_price: 1199,
    category: "tshirt",
    average_product_rating: 4,
    image_url: "https://m.media-amazon.com/images/I/51ONSEelkCL._SL1200_.jpg",
    brand: "puma",
    num_reviews: 4,
    Avaiable: true,
    Stocks: 120,
    keywords: ["tshirt", "clothing", "puma"],
    deliveryInDays: 1,
    cod: true,
    gender: "mens",
  },
  {
    id: 7,
    sku: "pp5004050433",
    name: "TURMS Cotton Rich Jeans 30 Days No Wash Casual Jeans",
    description:
      "TURMS Adventure Comfort Denim Jeans for Men. Stretchable cotton-rich jeans with anti-odor and anti-stain technology, allowing for 30 days of wear without washing. Casual, mid-rise style for ultimate comfort.",
    list_price: 3999,
    sale_price: 3134,
    category: "jeans",
    average_product_rating: 3.8,
    image_url: "https://m.media-amazon.com/images/I/61SdSD+DjfL._SX679_.jpg",
    brand: "TURMS",
    num_reviews: 20,
    Avaiable: true,
    Stocks: 78,
    keywords: ["jeans", "clothing", "turms"],
    deliveryInDays: 2,
    cod: true,
    gender: "mens",
  },
  {
    id: 8,
    sku: "pp5005141413",
    name: "HP Pavilion 15, Ryzen 5 5625U, 15.6 inch(39.6cm) , 8GB RAM,512GB SSD",
    description:
      "The HP Pavilion 15-eh2050au boasts a sleek design and robust performance, driven by its Ryzen 5 5625U processor. Its 15.6-inch Full HD display offers vibrant visuals, complemented by 8GB RAM and a 512GB SSD for seamless multitasking and ample storage. With AMD Radeon graphics and B&O audio, it delivers an immersive entertainment experience. Enhanced usability is ensured by the backlit keypad, Windows 11 OS, and Alexa integration, all packed into a lightweight 1.75 kg frame in Natural Silver.",
    list_price: 61886,
    sale_price: 49990,
    category: "laptop",
    average_product_rating: 4.2,
    image_url: "https://m.media-amazon.com/images/I/71sLlEcQT6L._SL1500_.jpg",
    brand: "HP",
    num_reviews: 247,
    Avaiable: true,
    Stocks: 24,
    keywords: ["laptop", "electronics", "hp"],
    deliveryInDays: 1,
    cod: true,
    gender: "universal",
  },
  {
    id: 9,
    sku: "pp5007310136",
    name: "MSI Stealth 17 Studio, Intel 13th Gen. i9-13900H, 43CM FHD 144Hz Mini LED, HDR 1000 Gaming Laptop",
    description:
      'The MSI Stealth 17 Studio A13VH-055IN is a powerhouse gaming laptop featuring an Intel i9-13900H processor,17" FHD 144Hz Mini LED display with HDR 1000, Nvidia GeForce RTX4080 GPU, 64GB RAM, and 2TB NVMe SSD. With Windows 11 Home, it offers top-tier performance in a sleek Core Black design, weighing just 3.3kg. ',
    list_price: 492990,
    sale_price: 489883,
    category: "laptop",
    average_product_rating: 7,
    image_url: "https://m.media-amazon.com/images/I/71J1J8q04NL._SL1500_.jpg",
    brand: "MSI",
    num_reviews: 2,
    Avaiable: true,
    Stocks: 24,
    keywords: ["laptop", "electronics", "msi"],
    deliveryInDays: 1,
    cod: true,
    gender: "universal",
  },
  {
    id: 10,
    sku: "pp5006081510",
    name: "Dell Alienware x16 Gaming Laptop, Intel Core i9 13900HK Processor",
    description:
      "The Dell Alienware x16 Gaming Laptop packs a punch with an Intel Core i9 13900HK CPU, 32GB RAM, and a massive 2TB SSD. Its NVIDIA RTX 4090 GPU delivers stunning graphics on a 16\" QHD+ display. With Windows 11, Microsoft Office '21, and McAfee security, it's a powerhouse in a sleek Lunar Silver design, weighing just 2.72kg.",
    list_price: 547508,
    sale_price: 453230,
    category: "laptop",
    average_product_rating: 4.9,
    image_url:
      "https://m.media-amazon.com/images/I/31kNZoOdv4L._SX300_SY300_QL70_FMwebp_.jpg",
    brand: "Dell",
    num_reviews: 10,
    Avaiable: false,
    Stocks: 0,
    keywords: ["laptop", "electronics", "dell"],
    deliveryInDays: 1,
    cod: true,
    gender: "universal",
  },
  {
    id: 11,
    sku: "pp5005090292",
    name: "Fisher-Price Plush Dog Baby Toy with Lights Music",
    description:
      "Introducing Hemley's Plush Dog Toy - the ultimate companion for your little one! With captivating lights, delightful music, and interactive smart stages learning content, Laugh & Learn Sis engages and educates while providing endless cuddles. Encourage early development and imaginative play with this adorable and stimulating toy!",
    list_price: 3999,
    sale_price: 3599,
    category: "toys",
    average_product_rating: 4.3,
    image_url: "https://m.media-amazon.com/images/I/81HZhgtCoIL._SL1500_.jpg",
    brand: "hemleys",
    num_reviews: 3,
    Avaiable: true,
    Stocks: 544,
    keywords: ["toys", "hemleys"],
    deliveryInDays: 3,
    cod: true,
    gender: "universal",
  },
  {
    id: 12,
    sku: "pp5003191169",
    name: "Shumee Wooden DIY Maker Set (3 Years+) ",
    description:
      "Introducing the Shumee Wooden DIY Maker Set by Hemley, the perfect toy for budding young builders aged 3 years and up! This STEM toy encourages creativity and problem-solving skills through hands-on building and constructive play. Crafted from high-quality wood, this set includes everything your child needs to unleash their imagination and construct endless creations.",
    list_price: 3995,
    sale_price: 3555,
    category: "toys",
    average_product_rating: 4.7,
    image_url: "https://m.media-amazon.com/images/I/612oF1rFrOL._SL1200_.jpg",
    brand: "hemleys",
    num_reviews: 78,
    Avaiable: true,
    Stocks: 248,
    keywords: ["toys", "hemleys"],
    deliveryInDays: 3,
    cod: true,
    gender: "universal",
  },
  {
    id: 13,
    sku: "pp5006310386",
    name: "BEAU STUTI Battling Top Bey Set with Launcher",
    description:
      "Introducing the BEAU STUTI Battling Top Bey Set featuring the formidable Vanish Fafnir! This exciting set includes a powerful launcher and everything you need to engage in thrilling battles. Vanish Fafnir is ready to spin into action, facing off against other tops in epic showdowns. With its durable construction and high-performance capabilities, this Bey is sure to impress fans of all ages.",
    list_price: 999,
    sale_price: 699,
    category: "toys",
    average_product_rating: 4.8,
    image_url: "https://m.media-amazon.com/images/I/61orhtzGNEL.jpg",
    brand: "BEAU STUTI",
    num_reviews: 123,
    Avaiable: true,
    Stocks: 248,
    keywords: ["toys", "BEAU STUTI"],
    deliveryInDays: 2,
    cod: true,
    gender: "universal",
  },
  {
    id: 14,
    sku: "pp5006380171",
    name: "Tommy Hilfiger Vihaan Leather Global Coin Wallet for Men",
    description:
      "Elevate your everyday style with the Tommy Hilfiger Vihaan Leather Global Coin Wallet for Men in sleek navy. Crafted from premium leather, this wallet boasts four card slots for easy organization and a sophisticated global coin pocket. Its timeless design is complemented by the iconic Tommy Hilfiger logo, offering both functionality and fashion-forward appeal",
    list_price: 2800,
    sale_price: 1260,
    category: "wallet",
    average_product_rating: 4.6,
    image_url: "https://m.media-amazon.com/images/I/71UkL+SX2gL._SL1500_.jpg",
    brand: "Tommy Hilfiger",
    num_reviews: 46,
    Avaiable: true,
    Stocks: 89,
    keywords: ["wallet", "lifestyle", "Tommy Hilfiger"],
    deliveryInDays: 1,
    cod: true,
    gender: "mens",
  },
  {
    id: 15,
    sku: "pp5005070230",
    name: "Sea Dweller - Rolex",
    description:
      "Guaranteed waterproof to a depth of 610 metres (2,000 feet) when it was launched in 1967, then to 1,220 metres (4,000 feet) from 1978, the Sea‑Dweller combines all the attributes of the modern divers’ watch. Tested in real-life conditions as part of the Tektite programme, initiated jointly by NASA, the US Navy and the US Government in 1969, the Sea‑Dweller accompanied the first major experiments with underwater habitats.",
    list_price: 1790900,
    sale_price: 1594500,
    category: "watch",
    average_product_rating: 4.9,
    image_url:
      "https://media.rolex.com/image/upload/q_auto/f_auto/t_v7/c_limit,w_1920/v1/catalogue/2024/upright-c/m126603-0001",
    brand: "Rolex",
    num_reviews: 8900,
    Avaiable: true,
    Stocks: 9,
    keywords: ["watch", "lifestyle", "rolex"],
    deliveryInDays: 4,
    cod: true,
    gender: "mens",
  },
  {
    id: 16,
    sku: "1d21ed8",
    name: "Lady - Datejust",
    description:
      "The women's version of this date chronometer, the Lady-Datejust carries the elegance of the Datejust in a small size perfectly suited to a slender wrist. Oyster, 28 mm, Everose gold and diamonds, Monobloc middle case, screw-down case back and winding crown, Waterproof to 100 metres / 330 feet",
    list_price: 3966780,
    sale_price: 3789000,
    category: "watch",
    average_product_rating: 4.8,
    image_url:
      "https://media.rolex.com/image/upload/q_auto/f_auto/t_v7/c_limit,w_1920/v1/catalogue/2024/upright-c/m279135rbr-0001",
    brand: "Rolex",
    num_reviews: 7845,
    Avaiable: true,
    Stocks: 39,
    keywords: ["watch", "lifestyle", "rolex"],
    deliveryInDays: 2,
    cod: true,
    gender: "womens",
  },
  {
    id: 17,
    sku: "pp5007310136",
    name: "Bobster Alpha BALP101 Goggle Sunglasses",
    description:
      "Introducing the Bobster Alpha BALP101 Goggle Sunglasses, designed for versatility and performance in any outdoor adventure. Featuring a sleek black frame and interchangeable smoke and clear lenses, these goggles offer exceptional protection and visibility in various lighting conditions. Whether you're cruising down the highway or hitting the slopes, the Bobster Alpha BALP101 Goggle Sunglasses are the perfect companion for your active lifestyle.",
    list_price: 27673,
    sale_price: 25679,
    category: "goggles",
    average_product_rating: 5,
    image_url:
      "http://s7d9.scene7.com/is/image/JCPenney/DP1202201517023245M.tif?hei=380&amp;wid=380&op_usm=.4,.8,0,0&resmode=sharp2&op_usm=1.5,.8,0,0&resmode=sharp",
    brand: "Bobster",
    num_reviews: 45,
    Avaiable: true,
    Stocks: 48,
    keywords: ["goggles", "lifestyle", "bobster"],
    deliveryInDays: 2,
    cod: true,
    gender: "universal",
  },
  {
    id: 18,
    sku: "pp5006320708",
    name: "Motorola g64 5G (Mint Green, 128 GB) (8 GB RAM)",
    description:
      "The Motorola G64 5G in Mint Green offers a seamless blend of style and performance. With its 128 GB of storage and 8 GB of RAM, it ensures ample space for your apps, media, and multitasking needs. Experience lightning-fast connectivity with 5G capability, enabling smooth browsing, streaming, and gaming. Motorola's renowned craftsmanship guarantees durability and reliability, while its sleek design adds a touch of elegance to your everyday tech companion.",
    list_price: 18999,
    sale_price: 16599,
    category: "mobile",
    average_product_rating: 4.5,
    image_url: "https://m.media-amazon.com/images/I/71-QQkEiT0L._SL1500_.jpg",
    brand: "Motorola",
    num_reviews: 82,
    Avaiable: true,
    Stocks: 201,
    keywords: ["mobile", "electronics", "motorola"],
    deliveryInDays: 1,
    cod: true,
    gender: "universal",
  },
  {
    id: 19,
    sku: "pp5007210064",
    name: "Samsung Galaxy Tab A9+ 27.94 cm",
    description:
      "The Samsung Galaxy Tab A9+ offers a spacious 11.0-inch display, providing immersive viewing experiences for entertainment, work, and more. With a generous 8GB of RAM, multitasking is seamless, ensuring smooth performance even with multiple apps running simultaneously. Its 128GB of internal storage provides ample space for your apps, photos, videos, and documents, and it's expandable via microSD card for additional storage flexibility.",
    list_price: 27900,
    sale_price: 20900,
    category: "tablet",
    average_product_rating: 4.1,
    image_url: "https://m.media-amazon.com/images/I/61afkty1foL._SL1500_.jpg",
    brand: "samsung",
    num_reviews: 56,
    Avaiable: true,
    Stocks: 3,
    keywords: ["tablet", "electronics", "samsung"],
    deliveryInDays: 1,
    cod: true,
    gender: "universal",
  },
  {
    id: 20,
    sku: "pp5005710134",
    name: "Tommy Hilfiger Women's T-Shirt",
    description:
      "Elevate your casual wardrobe with the timeless style of the Tommy Hilfiger Women's T-Shirt. Crafted from soft and comfortable fabric, this t-shirt offers a flattering fit and all-day comfort. It features the iconic Tommy Hilfiger logo for a touch of signature flair. With its classic design and quality construction, this t-shirt is perfect for everyday wear, whether you're running errands or relaxing with friends.",
    list_price: 1999,
    sale_price: 1999,
    category: "tshirt",
    average_product_rating: 4.8,
    image_url: "https://m.media-amazon.com/images/I/61Ou3B8+u8L._SL1500_.jpg",
    brand: "Tommy Hilfiger",
    num_reviews: 60,
    Avaiable: true,
    Stocks: 300,
    keywords: ["tshirt", "clothing", "Tommy Hilfiger"],
    deliveryInDays: 3,
    cod: true,
    gender: "womens",
  },
];
